cursos = [
    "Administracao",
    "Administracao UAST",
    "Agronomia",
    "Agronomia UAST",
    "Bacharelado em Agroecologia",
    "Bacharelado em Ciencia da Computacao",
    "Bacharelado em Ciencias Biologicas",
    "Bacharelado em Ciencias Biologicas - UAST",
    "Bacharelado em Ciencias do Consumo",
    "Bacharelado em Ciencias Economicas",
    "Bacharelado em Ciencias Economicas - UAST",
    "Bacharelado em Ciencias Sociais",
    "Bacharelado em Gastronomia",
    "Bacharelado em Sistemas da Informacao",
    "Bacharelado em Sistemas da Informacao - UAST",
    "Economia Domestica",
    "Engenharia Agricola e Ambiental",
    "Engenharia Ambiental",
    "Engenharia Civil - UACSA",
    "Engenharia da Computacao - Belo Jardim",
    "Engenharia de Controle e Automacao - Belo Jardim",
    "Engenharia de Materiais- UACSA",
    "Engenharia de Pesca",
    "Engenharia de Pesca - UAST",
    "Engenharia Eletrica - UACSA",
    "Engenharia Eletronica - UACSA",
    "Engenharia Florestal",
    "Engenharia Hidrica - Belo Jardim",
    "Engenharia Mecanica - UACSA",
    "Engenharia Quimica - Belo Jardim",
    "Licenciatura em Ciencias Biologicas",
    "Licenciatura em Computacao",
    "Licenciatura em Educacao Fisica",
    "Licenciatura em Fisica",
    "Licenciatura em Historia",
    "Licenciatura em Letras (Portugues e Espanhol)",
    "Licenciatura em Matematica",
    "Licenciatura em Pedagogia",
    "Licenciatura em Quimica",
    "Licenciatura em Quimica - UAST",
    "Medicina Veterinaria",
    "Tecnologia em Aquicultura",
    "Zootecnia",
    "Zootecnia - UAST"
]